
package pl.edu.agh.backmainapp.webservice;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "NotifyMainModuleBean", targetNamespace = "http://webService.backMainApp.agh.edu.pl/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface NotifyMainModuleBean {


    /**
     * 
     * @param areaId
     * @param spotId
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "notifyaddSpot", targetNamespace = "http://webService.backMainApp.agh.edu.pl/", className = "pl.edu.agh.backmainapp.webservice.NotifyaddSpot")
    @ResponseWrapper(localName = "notifyaddSpotResponse", targetNamespace = "http://webService.backMainApp.agh.edu.pl/", className = "pl.edu.agh.backmainapp.webservice.NotifyaddSpotResponse")
    public String notifyaddSpot(
        @WebParam(name = "AreaId", targetNamespace = "")
        String areaId,
        @WebParam(name = "SpotId", targetNamespace = "")
        String spotId);

    /**
     * 
     * @param areaId
     * @param spotId
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "notifyOccupySpot", targetNamespace = "http://webService.backMainApp.agh.edu.pl/", className = "pl.edu.agh.backmainapp.webservice.NotifyOccupySpot")
    @ResponseWrapper(localName = "notifyOccupySpotResponse", targetNamespace = "http://webService.backMainApp.agh.edu.pl/", className = "pl.edu.agh.backmainapp.webservice.NotifyOccupySpotResponse")
    public String notifyOccupySpot(
        @WebParam(name = "AreaId", targetNamespace = "")
        String areaId,
        @WebParam(name = "SpotId", targetNamespace = "")
        String spotId);

    /**
     * 
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "notifyPrintSpots", targetNamespace = "http://webService.backMainApp.agh.edu.pl/", className = "pl.edu.agh.backmainapp.webservice.NotifyPrintSpots")
    @ResponseWrapper(localName = "notifyPrintSpotsResponse", targetNamespace = "http://webService.backMainApp.agh.edu.pl/", className = "pl.edu.agh.backmainapp.webservice.NotifyPrintSpotsResponse")
    public String notifyPrintSpots();

    /**
     * 
     * @param areaId
     * @param spotId
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "notifyVacateSpot", targetNamespace = "http://webService.backMainApp.agh.edu.pl/", className = "pl.edu.agh.backmainapp.webservice.NotifyVacateSpot")
    @ResponseWrapper(localName = "notifyVacateSpotResponse", targetNamespace = "http://webService.backMainApp.agh.edu.pl/", className = "pl.edu.agh.backmainapp.webservice.NotifyVacateSpotResponse")
    public String notifyVacateSpot(
        @WebParam(name = "AreaId", targetNamespace = "")
        String areaId,
        @WebParam(name = "SpotId", targetNamespace = "")
        String spotId);

    /**
     * 
     * @param areaId
     * @param spotId
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "notifyRemoveSpot", targetNamespace = "http://webService.backMainApp.agh.edu.pl/", className = "pl.edu.agh.backmainapp.webservice.NotifyRemoveSpot")
    @ResponseWrapper(localName = "notifyRemoveSpotResponse", targetNamespace = "http://webService.backMainApp.agh.edu.pl/", className = "pl.edu.agh.backmainapp.webservice.NotifyRemoveSpotResponse")
    public String notifyRemoveSpot(
        @WebParam(name = "AreaId", targetNamespace = "")
        String areaId,
        @WebParam(name = "SpotId", targetNamespace = "")
        String spotId);

}
