
package pl.edu.agh.backmainapp.webservice;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "NotifyMainModuleBeanService", targetNamespace = "http://webService.backMainApp.agh.edu.pl/", wsdlLocation = "http://localhost:8080/Parkometr2017-1.0/NotifyMainModuleBean?wsdl")
public class NotifyMainModuleBeanService
    extends Service
{

    private final static URL NOTIFYMAINMODULEBEANSERVICE_WSDL_LOCATION;
    private final static WebServiceException NOTIFYMAINMODULEBEANSERVICE_EXCEPTION;
    private final static QName NOTIFYMAINMODULEBEANSERVICE_QNAME = new QName("http://webService.backMainApp.agh.edu.pl/", "NotifyMainModuleBeanService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8080/Parkometr2017-1.0/NotifyMainModuleBean?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        NOTIFYMAINMODULEBEANSERVICE_WSDL_LOCATION = url;
        NOTIFYMAINMODULEBEANSERVICE_EXCEPTION = e;
    }

    public NotifyMainModuleBeanService() {
        super(__getWsdlLocation(), NOTIFYMAINMODULEBEANSERVICE_QNAME);
    }

    public NotifyMainModuleBeanService(WebServiceFeature... features) {
        super(__getWsdlLocation(), NOTIFYMAINMODULEBEANSERVICE_QNAME, features);
    }

    public NotifyMainModuleBeanService(URL wsdlLocation) {
        super(wsdlLocation, NOTIFYMAINMODULEBEANSERVICE_QNAME);
    }

    public NotifyMainModuleBeanService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, NOTIFYMAINMODULEBEANSERVICE_QNAME, features);
    }

    public NotifyMainModuleBeanService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public NotifyMainModuleBeanService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns NotifyMainModuleBean
     */
    @WebEndpoint(name = "NotifyMainModuleBeanPort")
    public NotifyMainModuleBean getNotifyMainModuleBeanPort() {
        return super.getPort(new QName("http://webService.backMainApp.agh.edu.pl/", "NotifyMainModuleBeanPort"), NotifyMainModuleBean.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns NotifyMainModuleBean
     */
    @WebEndpoint(name = "NotifyMainModuleBeanPort")
    public NotifyMainModuleBean getNotifyMainModuleBeanPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://webService.backMainApp.agh.edu.pl/", "NotifyMainModuleBeanPort"), NotifyMainModuleBean.class, features);
    }

    private static URL __getWsdlLocation() {
        if (NOTIFYMAINMODULEBEANSERVICE_EXCEPTION!= null) {
            throw NOTIFYMAINMODULEBEANSERVICE_EXCEPTION;
        }
        return NOTIFYMAINMODULEBEANSERVICE_WSDL_LOCATION;
    }

}
