
package pl.edu.agh.backmainapp.webservice;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "NotifyMainModuleBean", targetNamespace = "http://webService.backMainApp.agh.edu.pl/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface NotifyMainModuleBean {


    /**
     * 
     * @param arg1
     * @param arg0
     */
    @WebMethod
    @RequestWrapper(localName = "notifyaddSpot", targetNamespace = "http://webService.backMainApp.agh.edu.pl/", className = "pl.edu.agh.backmainapp.webservice.NotifyaddSpot")
    @ResponseWrapper(localName = "notifyaddSpotResponse", targetNamespace = "http://webService.backMainApp.agh.edu.pl/", className = "pl.edu.agh.backmainapp.webservice.NotifyaddSpotResponse")
    public void notifyaddSpot(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        String arg1);

    /**
     * 
     * @param arg1
     * @param arg0
     */
    @WebMethod
    @RequestWrapper(localName = "notifyOccupySpot", targetNamespace = "http://webService.backMainApp.agh.edu.pl/", className = "pl.edu.agh.backmainapp.webservice.NotifyOccupySpot")
    @ResponseWrapper(localName = "notifyOccupySpotResponse", targetNamespace = "http://webService.backMainApp.agh.edu.pl/", className = "pl.edu.agh.backmainapp.webservice.NotifyOccupySpotResponse")
    public void notifyOccupySpot(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        String arg1);

    /**
     * 
     * @param arg1
     * @param arg0
     */
    @WebMethod
    @RequestWrapper(localName = "notifyRemoveSpot", targetNamespace = "http://webService.backMainApp.agh.edu.pl/", className = "pl.edu.agh.backmainapp.webservice.NotifyRemoveSpot")
    @ResponseWrapper(localName = "notifyRemoveSpotResponse", targetNamespace = "http://webService.backMainApp.agh.edu.pl/", className = "pl.edu.agh.backmainapp.webservice.NotifyRemoveSpotResponse")
    public void notifyRemoveSpot(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        String arg1);

}
